plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\tomma\\Desktop\\01_PROGETTI\\KREA\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npx vite build --base=/"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]